name: Deploy Laravel Application

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          passphrase: ${{ secrets.HOSTINGER_SSH_PASSPHRASE }}
          port: 22
          debug: true
          script: |
            mkdir -p /home/user/htdocs
            cd /home/user/htdocs
            if [ ! -d "srv656676.hstgr.cloud" ]; then
              git clone ${{ secrets.REPO_URL }} srv656676.hstgr.cloud
              cd srv656676.hstgr.cloud
            else
              cd srv656676.hstgr.cloud
              git clean -fd
              git reset --hard HEAD
              git fetch origin main
              git reset --hard origin/main
            fi

            sudo chown -R user:user .
            sudo chmod -R 755 .
            sudo chmod -R 777 storage bootstrap/cache

            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-interaction --no-plugins --no-scripts
            npm install
            npm run build

            php artisan down

            # Update Supervisor configurations
            sudo cp deployment/supervisor/*.conf /etc/supervisor/conf.d/
            sudo supervisorctl reread
            sudo supervisorctl update

            # Update Crontab for scheduler
            crontab -l | grep -v "artisan schedule:run" | crontab -
            (crontab -l 2>/dev/null; echo "* * * * * cd /home/user/htdocs/srv656676.hstgr.cloud && php artisan schedule:run >> /home/user/htdocs/srv656676.hstgr.cloud/storage/logs/scheduler.log 2>&1") | crontab -

            php artisan migrate --force
            # Force refresh database and run seeders
            php artisan migrate:fresh --force
            php artisan db:seed --force

            php artisan optimize:clear
            php artisan optimize

            # Restart queue workers
            sudo supervisorctl restart laravel-worker:*

            # Restart websocket server if using reverb
            sudo supervisorctl restart reverb:*

            # Clear schedule cache
            php artisan schedule:clear-cache

            # Restart queue
            php artisan queue:restart

            php artisan up
