name: Deploy Laravel Application

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          passphrase: ${{ secrets.HOSTINGER_SSH_PASSPHRASE }}
          port: 22
          debug: true
          script: |
            mkdir -p /home/user/htdocs
            cd /home/user/htdocs
            if [ ! -d "srv656676.hstgr.cloud" ]; then
              git clone ${{ secrets.REPO_URL }} srv656676.hstgr.cloud
              cd srv656676.hstgr.cloud
            else
              cd srv656676.hstgr.cloud
              git clean -fd
              git reset --hard HEAD
              git fetch origin main
              git reset --hard origin/main
            fi

            sudo chown -R user:user .
            sudo chmod -R 755 .
            sudo chmod -R 777 storage bootstrap/cache

            export COMPOSER_ALLOW_SUPERUSER=1
            composer install --no-interaction --no-plugins --no-scripts
            npm install
            npm run build

            php artisan down
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan up
            php artisan queue:restart

            sudo supervisorctl stop reverb:*
            sudo supervisorctl start reverb:*
