name: Deploy Laravel Application

on:
  push:
    branches: [ "main" ]  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Adjust this to match your VPS PHP version

    - name: Deploy to Hostinger VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_HOST }}
        username: ${{ secrets.HOSTINGER_USERNAME }}
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        passphrase: ${{ secrets.HOSTINGER_SSH_PASSPHRASE }}
        port: 22  # Default SSH port for Hostinger VPS
        debug: true
        script: |
          cd /home/user/htdocs/srv656676.hstgr.cloud
          git pull origin main
          composer install
          php artisan down
          php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          chown -R www-data:www-data .  # Fix permissions for Ubuntu
          php artisan up  # Bring application back online
